// The charm catalogue. Art lives in ./charms/<id>.svg (viewBox 0 0 200 200,
// hung from the top centre). `weight` changes how charms push each other;
// `hook` is how far down the art starts, bridged by a small metal link.

export const COLLECTIONS = [
  {
    id: 'kawaii',
    name: 'Mochi & Friends',
    tagline: 'Soft, sweet, a little bit extra.',
    blurb: 'Pastel kitties, bunnies and snacks that smile back at you.',
    accent: '#ff8fbf',
    charms: [
      ['mochi-kitty', 'Mochi Kitty', 1, 54],
      ['pink-bow', 'Pink Bow', 1, 68],
      ['strawberry', 'Berry'],
      ['bunny', 'Bun Bun', 1, 84],
      ['boba-tea', 'Boba'],
      ['sleepy-cloud', 'Sleepy Cloud', 1, 64],
    ],
  },
  {
    id: 'good-boys',
    name: 'Good Boys',
    tagline: 'Who’s a good boy? All of them.',
    blurb: 'Golden retrievers, a corgi, a shiba and a very shiny paw.',
    accent: '#f1b45c',
    charms: [
      ['golden-retriever', 'Goldie', 1, 20],
      ['golden-pup', 'Sunny Pup', 1, 38],
      ['corgi', 'Corgi', 1, 58],
      ['shiba', 'Shiba', 1, 54],
      ['gold-paw', 'Golden Paw', 1.4, 14],
      ['bone-tag', 'Good Boy Tag', 1.2],
    ],
  },
  {
    id: 'aviation',
    name: 'Cleared for Takeoff',
    tagline: 'For pilots, crew and window-seat people.',
    blurb: 'Airliners, jets, a vintage prop plane and your wings.',
    accent: '#6ea8ff',
    charms: [
      ['airliner', 'Airliner', 1.3],
      ['prop-plane', 'Vintage Prop', 1, 60],
      ['jet', 'Fighter Jet', 1.3],
      ['pilot-wings', 'Pilot Wings', 1.4],
      ['hot-air-balloon', 'Balloon', 0.8],
      ['compass', 'Compass', 1.5],
      ['paper-plane', 'Paper Plane', 0.6],
    ],
  },
  {
    id: 'protection',
    name: 'Protection',
    tagline: 'Good energy, always.',
    blurb: 'The nazar, a hamsa, nimbu-mirchi and a little luck.',
    accent: '#3f7bff',
    charms: [
      ['nazar', 'Nazar', 1.2],
      ['hamsa', 'Hamsa', 1.2],
      ['nimbu-mirchi', 'Nimbu Mirchi'],
      ['clover', 'Four-Leaf Clover', 0.8],
      ['horseshoe', 'Horseshoe', 1.5],
    ],
  },
  {
    id: 'celestial',
    name: 'Celestial',
    tagline: 'A little sky, indoors.',
    blurb: 'A sleepy moon, a sunny sun, Saturn and a happy star.',
    accent: '#ffd35f',
    charms: [
      ['moon', 'Sleepy Moon', 1, 24],
      ['sun', 'Sunshine'],
      ['saturn', 'Saturn', 1, 50],
      ['star', 'Lucky Star'],
    ],
  },
  {
    id: 'wild',
    name: 'Wild Ones',
    tagline: 'A tiny safari on your screen.',
    blurb: 'Lions, tigers, pandas and friends, softened into round little faces.',
    accent: '#f0a04a',
    charms: [
      ['lion', 'Leo the Lion', 1.1, 8],
      ['tiger', 'Tiger', 1, 40],
      ['panda', 'Panda', 1, 44],
      ['elephant', 'Elephant', 1.3, 22],
      ['fox', 'Fox', 1, 52],
      ['owl', 'Owl', 1, 30],
      ['penguin', 'Penguin', 1, 12],
      ['giraffe', 'Giraffe', 1, 18],
    ],
  },
  {
    id: 'football',
    name: 'Matchday',
    tagline: 'For the ones who never miss kick-off.',
    blurb: 'Our own cartoon striker and keeper, plus the ball, the boot and the cup.',
    accent: '#3ecf6e',
    charms: [
      ['striker', 'Striker #10', 1, 14],
      ['keeper', 'Keeper #1', 1, 12],
      ['football', 'Football', 1, 18],
      ['golden-boot', 'Golden Boot', 1.4],
      ['trophy', 'Trophy', 1.5, 14],
      ['jersey', 'Jersey #7', 0.8],
      ['whistle', 'Whistle', 1.2],
    ],
  },
  {
    id: 'heroes',
    name: 'Heroes',
    tagline: 'Capes optional. Courage required.',
    blurb: 'An original caped kid, a mask, a bolt, a shield and a big comic POW!',
    accent: '#ff5a4a',
    charms: [
      ['cape-kid', 'Cape Kid', 1, 14],
      ['hero-mask', 'Hero Mask', 0.8],
      ['bolt-emblem', 'Bolt Emblem', 1.3, 8],
      ['winged-shield', 'Winged Shield', 1.4, 16],
      ['power-gem', 'Power Gem', 1.2],
      ['pow-burst', 'POW!', 1, 6],
    ],
  },
  {
    id: 'lab',
    name: 'Lab & Desert',
    tagline: 'Say my… element.',
    blurb: 'Flasks, blue crystals, a gold tile, a cactus and a camper in the desert.',
    accent: '#4fc3e8',
    charms: [
      ['flask', 'Flask', 1, 16],
      ['crystals', 'Blue Crystals', 1.2],
      ['beaker', 'Beaker'],
      ['au-tile', 'Gold (Au)', 1.4],
      ['cactus', 'Cactus'],
      ['camper', 'Desert Camper', 1.3],
    ],
  },
  {
    id: 'eighties',
    name: 'Upside Down ’80s',
    tagline: 'Something strange is on your desktop.',
    blurb: 'Walkie-talkies, BMX bikes, fairy lights, waffles and a lucky D20.',
    accent: '#e8344e',
    charms: [
      ['walkie-talkie', 'Walkie-Talkie', 1.1, 54],
      ['bmx', 'BMX', 1.2],
      ['fairy-lights', 'Fairy Lights', 0.7],
      ['waffle', 'Waffle'],
      ['d20', 'D20', 1.2],
      ['cassette', 'Mixtape'],
    ],
  },
  {
    id: 'luxe',
    name: 'Luxe',
    tagline: 'Quiet luxury, loud sparkle.',
    blurb: 'Diamonds, pearls, perfume, a gold watch and a little bubbly.',
    accent: '#e2b040',
    charms: [
      ['diamond-ring', 'Diamond Ring', 1.3],
      ['pearl-necklace', 'Pearls', 1.1],
      ['perfume', 'Parfum'],
      ['quilted-bag', 'Top-Handle Bag', 1, 42],
      ['gold-watch', 'Gold Watch', 1.5],
      ['stiletto', 'Stiletto'],
      ['champagne', 'Champagne', 1.3],
    ],
  },
  {
    id: 'coders',
    name: 'Dev Mode',
    tagline: 'It works on my desktop.',
    blurb: 'A laptop, a rubber duck, a friendly bug, a terminal and a coffee loop.',
    accent: '#7ee0a8',
    charms: [
      ['laptop', 'Laptop', 1.2],
      ['coffee-mug', 'Coffee Loop'],
      ['rubber-duck', 'Rubber Duck', 0.8],
      ['bug', 'Friendly Bug'],
      ['terminal', 'Terminal', 1.1],
      ['braces', 'Curly Braces'],
      ['git-branch', 'Git Branch', 1.1],
    ],
  },
  {
    id: 'doctors',
    name: 'On Call',
    tagline: 'For the people who keep us ticking.',
    blurb: 'A stethoscope, a beating heart, a smiley pill, a tooth, DNA and a big brain.',
    accent: '#2ec4a8',
    charms: [
      ['stethoscope', 'Stethoscope', 1, 2],
      ['ecg-heart', 'Heartbeat'],
      ['pill', 'Happy Pill'],
      ['med-cross', 'Care Cross', 1.1],
      ['tooth', 'Tooth'],
      ['dna', 'DNA'],
      ['brain', 'Big Brain'],
    ],
  },
].map((col) => ({
  ...col,
  charms: col.charms.map(([id, name, weight = 1, hook = 0]) => ({
    id,
    name,
    weight,
    hook, // y (viewBox units) where the art actually starts under the ring
    collection: col.id,
    file: `${id}.svg`,
  })),
}));

export const ALL_CHARMS = COLLECTIONS.flatMap((c) => c.charms);

export function findCharm(id) {
  return ALL_CHARMS.find((c) => c.id === id) || null;
}

export const DEFAULT_CHARM = 'mochi-kitty';
